name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub (replace with your credentials)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull kapavan/cicd-kapavan:latest

      - name: Run Docker Container
        run: docker run kapavan/cicd-kapavan:latest

      - name: Check Score
        run: |
          score=$(docker run yourusername/yourimage:latest)
          if [[ $(echo "$score > 0.50" | bc) -eq 1 ]]; then
            echo "Score is greater than 0.50"
          else
            echo "Score is not greater than 0.50"
            exit 1
          fi
