name: Train

on:
  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (replace with your credentials)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t kapavan/cicd-kapavan:latest .
          docker push kapavan/cicd-kapavan:latest
  pull-and-run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub (replace with your credentials)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull kapavan/cicd-kapavan:latest

      - name: Check Score
        run: |
          score=$(docker run kapavan/cicd-kapavan:latest)
          echo "score:"
          echo "$score"
          echo "score end:"
          if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
    
